language: go

go:
  - 1.5

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

secure: "XicufHyE/FvOIiSHAVuC9DyZSruLZ7cJDkn9wXphMET8/5EVgADvaV6PWJQCPPDxkov+3J7+W1j7BtsOGvtNDFBMMETPMB4A6W7wTfnU2tznZ/nFkAHFBRI1cHaEuEjbd/0SwQ0kZ+CmGWEa5EazkXPSPU4PycSwzejrCL9UMWmePQh4V9cuflPsvnxM4WQUD2OHdiMidhdrIRTrqx9294LbDCX5NOTpr045i44mzPRwsq2QFXj0Hrtf2rASI90PIDXkhvcfG5l7aY44Ha6XSvNCAi6x3bke9n1JUrRYB07KUjyo7IYUECP3pukSgEPlbuv0Vj38h2vmC9NrV73/S5SCYajFHWUEN2XKR4k+EbVsMZUeEwINgMZDnjiEsYF42PCuJXVfWOR84QqkhDi2ysH40V/kKjZ4BR0oP1Jb868YVRhsEoRygjg9XFe9I7UnZLq38wH7H92tIdeKUYy3mwliGJOPm8SFUA9QTCr06rJC2oY4GN8hGIG29ENws0J0VT3/kSf8GlmXXCgS5RP56htVfgo0iaUWlODeBgROVn7C1G34vpjuiMEYRHiARREUYBsZX+rqfJaOJCqxHQ//WUpGOEdgozMXLCZjEyJ5ECvdoglww6JUSxmX8z0Ev/N9ZKLvfVZEGclzfQiB4rlhqodLlKnIrfwI4/kalQT1VxQ="

script:
  - $GOPATH/bin/goveralls -v -repotoken=$COVERALLS_TOKEN

notifications:
  email: false
  slack:
    secure: "Ie4osATAAugXyt5ee80NoPJO67+d1FJO8TuT2b6EX/ElB7jbePuZCDpUb+7Zry6ee6acJ7L3wWxSsySPIR6dW+iY4ljeM0fhT32qIkOyq7e72nppYKjzNFJvJScMLNp90N14e12CV9546heqablB/TFXvbnM6gAQpFxkdBlX+rUb21Zd3y99M2H+hT4qxB+6YPPPrf2FgMyMsFVav1ly7siAQpzlPFWCz0ugYFU9UQGrLKxHy2wHru+9kOz7R/CfpKm3U3RHftvZanX37kt2rJVGIpXgxRGef/hAiE/iRpJXXo/BnaGTKFt4sbpBZngEQl0RnmnVgdMHdf44xWoskpM0zDuhmq5neY5JevldP5e/ftqZ+PYOmxhUU3gZJzElOWCjTW3MGQFFAXALjJKvjXmAKB0F1lbfCKMI6P0IoovAw5i3tkGpKplPyfd+FZxSXXLN0D3KNZaxTyKQLehT/UZIxpj85WlmFbQgFuXxsaGKeDzbp/8qXbrYGmQq3Q0h3L3WlKq6Pj8HqGw741cExwKwDglgUNdmRCTtpUn2QbLzfFRDbsRkgUjUUiEaffIX24nNv6Ry3Fx7bDCUzfCt2/hziqliq7g3QLblPUcvv2dQRbJfxlh5axtmSKTVU0V08bW9fVnvJ2WLqiN2O+hFEvev1/xqKRvEeVLB5mKYkpI="
